# ================================================================================ #
# eORCA025_ERA5v1_GSR_config.toml
#
# Description: NOC NPD ERA5v1 eORCA025 configuration for NEMO pipeline 
# -> Greenland-Scotland Ridge section extraction.
# ================================================================================ #

[slurm]
# Define directories for SLURM job scripts and logs:
job_dir = "/dssgfs01/working/otooth/Software/nemo_pipeline/examples/NOC-NPD/eORCA025/outputs/jobs"
log_dir = "/dssgfs01/working/otooth/Software/nemo_pipeline/examples/NOC-NPD/eORCA025/outputs/logs"
log_prefix = "eORCA025_ERA5_GSR"

[slurm.sbatch]
# SLURM batch job submission parameters:
job_name = "nemo_pipeline_gsr"
time = "00:10:00"
partition = "test"
ntasks = 1
mem = "6G"

[slurm.jobs]
# Define Python virtual environment activation command:
venv_cmd = "source ~/miniforge3/bin/activate; conda activate env_nemo_cookbook"
# Define SLURM job type ("array" or "single"):
job_type = "array"

# Define the initial, final and step input patterns for batch job submission:
ip_start = 1976
ip_end = 2025
ip_step = 1
# Define maximum number of concurrent SLURM jobs:
max_concurrent_jobs = 5
# Kill the jobarray in the event of any job failure:
kill_on_fail = true

# ================================================================================ #

[inputs]
# Define NEMO ocean model filepaths used to construct NEMODataTree object:
nemo_dir = "/dssgfs01/scratch/npd/simulations/eORCA025_ERA5_v1"
domain_filepath = "/dssgfs01/scratch/npd/simulations/Domains/eORCA025/domain_cfg.nc"
# Create NEMO model grid datasets from CMORISED variables:
cmorised = false
# Domain Properties:
iperio = true
nftype = "F"
read_mask = false

[inputs.gridT]
# -- NEMO T-grid (scalar) variables -- #
filepath = "${nemo_dir}/eORCA025_ERA5_1m_grid_T_{ip}*.nc"
vars = [ "thetao_con", "so_abs" ]

[inputs.gridU]
# -- NEMO U-grid (zonal vector) variables -- #
filepath = "${nemo_dir}/eORCA025_ERA5_1m_grid_U_{ip}*.nc"
vars = [ "uo", "uo_eiv", "e3u" ]

[inputs.gridV]
# -- NEMO V-grid (meridional vector) variables -- #
filepath = "${nemo_dir}/eORCA025_ERA5_1m_grid_V_{ip}*.nc"
vars = [ "vo", "vo_eiv", "e3v" ]

[inputs.gridW]
# -- NEMO W-grid (vertical vector) variables -- #

[inputs.gridF]
# -- NEMO F-grid (vorticity vector) variables -- #

[inputs.icemod]
# -- NEMO icemod (sea-ice) variables -- #

# ================================================================================ #

[diagnostics]
# Define diagnostics to be computed using NEMODataTree:
diagnostic = { module = "nemo_pipeline.diagnostics.core", function = "extract_gsr_section" }
kwargs = { include_eiv = true }

# ================================================================================ #

[outputs]
# Define NEMO ocean model pipeline output file:
output_dir = "/dssgfs01/working/otooth/Software/nemo_pipeline/examples/NOC-NPD/eORCA025/outputs/GSR"
output_name = "eORCA025_ERA5_v1_GSR"
date_format = "M"
format = "netcdf"
# Define output dataset chunking:
chunks = { time_counter = 1, k = 75 }
