# ================================================================================ #
# eORCA12_ERA5v1_DAVIS_config.toml
#
# Description: NOC NPD ERA5v1 eORCA12 configuration for NEMO pipeline
# -> Davis Strait section extraction.
# ================================================================================ #

[slurm]
# Define directories for SLURM job scripts and logs:
job_dir = "/home/users/atb299/nemo_pipeline/examples/outputs/jobs"
log_dir = "/home/users/atb299/nemo_pipeline/examples/outputs/logs"
log_prefix = "eORCA12_ERA5_DAVIS"

[slurm.sbatch]
# SLURM batch job submission parameters:
job_name = "nemo_pipeline"
time = "02:10:00"
partition = "standard"
ntasks = 1
mem = "96G"
kwargs = { account = "nemo", qos = "standard" }

[slurm.jobs]
# Define Python virtual environment activation command:
venv_cmd = "source ~/.conda_init; conda activate env_nemo_cookbook"
# Define SLURM job type ("array" or "single"):
job_type = "array"

# Define the initial, final and step input patterns for batch job submission:
ip_start = 1976
ip_end = 2025
ip_step = 1
# Define maximum number of concurrent SLURM jobs:
max_concurrent_jobs = 2
# Kill the jobarray in the event of any job failure:
kill_on_fail = true

# ================================================================================ #

[inputs]
# Define NEMO ocean model filepaths used to construct NEMODataTree object:
nemo_dir = "/gws/nopw/j04/atlantis/atb299/NPD/eORCA12"
domain_filepath = "/gws/nopw/j04/atlantis/atb299/NPD/eORCA12/Domain/domain_cfg.nc"
# Create NEMO model grid datasets from CMORISED variables:
cmorised = false
# Domain Properties:
iperio = true
nftype = "T"
read_mask = false

[inputs.gridT]
# -- NEMO T-grid (scalar) variables -- #
filepath = "${nemo_dir}/{ip}/eORCA12_1m_grid_T_{ip}*.nc"
vars = [ "thetao_con", "so_abs" ]

[inputs.gridU]
# -- NEMO U-grid (zonal vector) variables -- #
filepath = "${nemo_dir}/{ip}/eORCA12_1m_grid_U_{ip}*.nc"
vars = [ "tauuo" ]

[inputs.gridV]
# -- NEMO V-grid (meridional vector) variables -- #
filepath = "${nemo_dir}/{ip}/eORCA12_1m_grid_V_{ip}*.nc"
vars = [ "vo", "e3v" ]

[inputs.gridW]
# -- NEMO W-grid (vertical vector) variables -- #

[inputs.gridF]
# -- NEMO F-grid (vorticity vector) variables -- #

[inputs.icemod]
# -- NEMO icemod (sea-ice) variables -- #

# ================================================================================ #

[diagnostics]
# Define diagnostics to be computed using NEMODataTree:
diagnostic = { module = "nemo_pipeline.diagnostics.core", function = "extract_zonal_section" }
kwargs = { lat = 67.33, lon_min = -63.31, lon_max = -50.41, tau_name = "tauuo", scalar_names = [ "thetao_con", "so_abs" ] }

# ================================================================================ #

[outputs]
# Define NEMO ocean model pipeline output file:
output_dir = "/gws/nopw/j04/nemo_vol1/atb299/EPOC/Sections/DAVIS"
output_name = "eORCA12_ERA5_v1_DAVIS"
date_format = "M"
format = "netcdf"
# Define output dataset chunking:
chunks = { time_counter = 1, k = 75 }
