# ================================================================================ #
# example_config.toml
#
# Description: Example configuration file for NEMO pipeline using SLURM job
# submission.
# ================================================================================ #

[slurm]
# Define directories for SLURM job scripts and logs:
job_dir = "/my/hpc/nemo_pipeline/examples/outputs/jobs"
log_dir = "/my/hpc/nemo_pipeline/examples/outputs/logs"
# Define log file prefix for SLURM job outputs:
log_prefix = "eORCA1_ERA5_OSNAP"

    [slurm.sbatch]
    # SLURM SBATCH submission directives:
    job_name = "nemo_pipeline_osnap"
    time = "00:10:00"
    partition = "standard"
    ntasks = 1
    mem = "6G"
    # Optional SLURM SBATCH submission directives:
    kwargs = { qos = "standard", account = "my_account" }

    [slurm.jobs]
    # Define Python virtual environment activation command:
    venv_cmd = "source ~/miniforge3/bin/activate; conda activate env_nemo"
    # Define SLURM job type ("array" or "single"):
    job_type = "single"
    # Define the initial, final and step input patterns {ip} for SLURM job arrays:
    ip_start = 2010
    ip_end = 2014
    ip_step = 1
    # Define maximum number of concurrent jobs for SLURM job arrays:
    max_concurrent_jobs = 2
    # Kill SLURM job array in the event of any job failure:
    kill_on_fail = true

# ================================================================================ #

[inputs]
# Define NEMO output directory and domain_cfg filepath to construct NEMODataTree:
nemo_dir = "/dssgfs01/scratch/npd/simulations/eORCA1_ERA5_v1"
domain_filepath = "/dssgfs01/scratch/npd/simulations/Domains/eORCA1/domain_cfg.nc"
# Create NEMO model grid datasets from CMORISED variables:
cmorised = false
# Input arguments to construct NEMODataTree:
iperio = true
nftype = "T"
read_mask = false

    [inputs.gridT]
    # -- NEMO gridT (scalar) variables -- #
    # Define filepath or list of filepaths with optional {ip} pattern to be substituted using --input-pattern argument:
    filepath = "${nemo_dir}/eORCA1_ERA5_1m_grid_T_{ip}*.nc"
    # Define list of variable names or list of list of variable names to be read from each file:
    vars = [ "thetao_con", "so_abs" ]
    # Define dictionary of chunks for all gridT variables:
    chunks = { k = 75 }

    [inputs.gridU]
    # -- NEMO gridU (zonal vector) variables -- #
    filepath = "${nemo_dir}/eORCA1_ERA5_1m_grid_U_{ip}*.nc"
    vars = [ "uo", "uo_eiv", "e3u" ]
    chunks = { k = 75 }

    [inputs.gridV]
    # -- NEMO gridV (meridional vector) variables -- #
    filepath = "${nemo_dir}/eORCA1_ERA5_1m_grid_V_{ip}*.nc"
    vars = [ "vo", "vo_eiv", "e3v" ]
    chunks = { k = 75 }

    [inputs.gridW]
    # -- NEMO gridW (vertical vector) variables -- #
    # filepath = "/path/to/eORCA_grid_W_{ip}*.nc"
    # vars = [ "my", "vars" ]

    [inputs.gridF]
    # -- NEMO gridF (vorticity vector) variables -- #
    # filepath = "/path/to/eORCA_grid_F_{ip}*.nc"
    # vars = [ "my", "vars" ]

    [inputs.icemod]
    # -- NEMO icemod (sea-ice) variables -- #
    # filepath = "/path/to/eORCA_icemod_{ip}*.nc"
    # vars = [ "my", "vars"]

# ================================================================================ #

[diagnostics]
# Define diagnostics to be computed using NEMODataTree:
diagnostic = { module = "nemo_pipeline.diagnostics.core", function = "extract_osnap_section" }
# Define keyword arguments to be passed to diagnostic function:
kwargs = { include_eiv = true }

# ================================================================================ #

[outputs]
# Define NEMO ocean model pipeline output file:
output_dir = "/my/hpc/nemo_pipeline/examples/outputs"
output_name = "eORCA1_ERA5_v1_OSNAP"
# Define date format for output files. Options are "Y" (YYYY), "M" (YYYY-MM) or "D" (YYYY-MM-DD):
date_format = "M"
# Define output file format ("netcdf" or "zarr"):
format = "netcdf"
# Define output dataset chunking:
chunks = { time_counter = 1, k = 75 }
